services:
  node1:
    build: .
    environment:
      NODE_ID: "node1"
      PORT: "9001"
      PEERS: "node2:9002,node3:9003,node4:9004,node5:9005"
    ports:
      - "9001:9001"

  node2:
    build: .
    environment:
      NODE_ID: "node2"
      PORT: "9002"
      PEERS: "node1:9001,node3:9003,node4:9004,node5:9005"
    ports:
      - "9002:9002"

  node3:
    build: .
    environment:
      NODE_ID: "node3"
      PORT: "9003"
      PEERS: "node1:9001,node2:9002,node4:9004,node5:9005"
    ports:
      - "9003:9003"

  node4:
    build: .
    environment:
      NODE_ID: "node4"
      PORT: "9004"
      PEERS: "node1:9001,node2:9002,node3:9003,node5:9005"
    ports:
      - "9004:9004"

  node5:
    build: .
    environment:
      NODE_ID: "node5"
      PORT: "9005"
      PEERS: "node1:9001,node2:9002,node3:9003,node4:9004"
    ports:
      - "9005:9005"
